directories:
  raw_data: "data/raw"
  processed_data: "data/processed"
  notebooks: "notebooks"
  output_data_description: "output/descriptives"
  output_kmeans: "output/kmeans"
  output_llama: "output/llama"

logging:
  level: "INFO"
  console_output: true
  log_file: "logs/predicting-market-reactions.log"

embedding:
  model: "distiluse-base-multilingual-cased-v1"
  available_models:
    - "paraphrase-MiniLM-L6-v2"
    - "paraphrase-multilingual-MiniLM-L12-v2"
    - "distiluse-base-multilingual-cased-v1"

clustering:
  kmeans:
    n_clusters: 10
  llama:
    # LLAMA-specific parameters can be added here

data:
  closing_time: "17:30:00"
  risk_free_file: "ESTR.csv"
  market_index: "^IBEX"

