"""Utility functions for text processing and financial calculations."""

from .financial import (
    FinancialUtilsError,
    calculate_annualized_return,
    calculate_annualized_volatility,
    calculate_beta,
    calculate_calmar_ratio,
    calculate_cumulative_return,
    calculate_cvar,
    calculate_excess_returns,
    calculate_information_ratio,
    calculate_max_drawdown,
    calculate_portfolio_statistics,
    calculate_sharpe_ratio,
    calculate_sortino_ratio,
    calculate_trading_costs,
    calculate_turnover,
    calculate_var,
)
from .text_processing import (
    calculate_text_statistics,
    capitalize_first_letter,
    contains_keywords,
    count_words,
    extract_numbers,
    extract_quoted_text,
    extract_sentences,
    normalize_whitespace,
    remove_email_addresses,
    remove_repeated_punctuation,
    remove_special_characters,
    remove_urls,
    truncate_text,
)

__all__ = [
    # Financial
    "FinancialUtilsError",
    "calculate_sharpe_ratio",
    "calculate_sortino_ratio",
    "calculate_calmar_ratio",
    "calculate_max_drawdown",
    "calculate_cumulative_return",
    "calculate_annualized_return",
    "calculate_annualized_volatility",
    "calculate_portfolio_statistics",
    "calculate_turnover",
    "calculate_trading_costs",
    "calculate_excess_returns",
    "calculate_information_ratio",
    "calculate_beta",
    "calculate_var",
    "calculate_cvar",
    # Text Processing
    "normalize_whitespace",
    "remove_urls",
    "remove_email_addresses",
    "truncate_text",
    "extract_sentences",
    "count_words",
    "extract_numbers",
    "contains_keywords",
    "remove_special_characters",
    "capitalize_first_letter",
    "remove_repeated_punctuation",
    "extract_quoted_text",
    "calculate_text_statistics",
]
